services:
  testememcached:
    image: testememcached
    build:
      context: .
      dockerfile: Dockerfile
  hazelcast:
    image: hazelcast/hazelcast:latest
    ports:
      - "5701:5701"
  management-center:
    image: hazelcast/management-center:5.6.0
    ports:
      - "8080:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
  aerospikedb:
    image: aerospike/aerospike-server:latest
    container_name: aerospike-server
    ports:
      - "3000-3002:3000-3002"
  memcached:
    image: memcached:alpine
    container_name: memcached_service
    ports:
      - "11211:11211"
    command: memcached -m 64 -u memcache